[package]
name = "1juhu/maze-of-mystery"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.6.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
Input = "sleitnick/input@2.3.0"
Component = "sleitnick/component@2.4.8"
Comm = "sleitnick/comm@1.0.1"
Suphi = "skylord-103/suphisdatastoremodule@1.0.0"
Fusion = "mattschrubb/fusion@1.2.5"
Roact = "roblox/roact@1.4.4"